name: Release on Tag
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build
        run: ./pack-ext.py ./
      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: 'glotdict@mte90.net'
          xpi-path: GlotDict_${{ steps.get_version.outputs.version }}.xpi
          jwt-issuer: ${{ secrets.FIREFOX_API_KEY }}
          jwt-secret: ${{ secrets.FIREFOX_API_SECRET }}
      - uses: wdzeng/chrome-extension@v1
        with:
            refresh-token: ${{ secrets.CHROME_API_TOKEN }}
            client-id: ${{ secrets.CHROME_API_ID }}
            client-secret: ${{ secrets.CHROME_API_SECRET }}
            zip-path: GlotDict_${{ steps.get_version.outputs.version }}.zip
            extension-id: ${{ secrets.CHROME_UUID }}
