name: Release on Tag
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Build
        run: ./pack-ext.py ./
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: 'glotdict@mte90.net'
          xpi: GlotDict_${{ steps.get_version.outputs.version }}.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
      - uses: trmcnvn/chrome-addon@v2
        with:
            refresh-token: ${{ secrets.CHROME_API_TOKEN }}
            client-id: ${{ secrets.CHROME_API_ID }}
            client-secret: ${{ secrets.CHROME_API_SECRET }}
            zip: GlotDict_${{ steps.get_version.outputs.version }}.zip
            extension: ${{ secrets.CHROME_UUID }}
